services:
  worker-1:
    build: .
    environment:
      - HTTP_PORT=8080
    env_file: .env
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db

  worker-2:
    build: .
    environment:
      - HTTP_PORT=8081
    env_file: .env
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - db

  worker-3:
    build: .
    environment:
      - HTTP_PORT=8082
    env_file: .env
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "${DB_PORT}:5432"
    restart: always

volumes:
  postgres_data:
