services:
  worker-1:
    build: .
    environment:
      - HTTP_PORT=8080
      - KAFKA_BROKERS=kafka:29092
      - OTEL_COLLECTOR_ENDPOINT=otel-collector:4317
    env_file: .env
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      otel-collector:
        condition: service_started

  worker-2:
    build: .
    environment:
      - HTTP_PORT=8081
      - KAFKA_BROKERS=kafka:29092
      - OTEL_COLLECTOR_ENDPOINT=otel-collector:4317
    env_file: .env
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      otel-collector:
        condition: service_started

  worker-3:
    build: .
    environment:
      - HTTP_PORT=8082
      - KAFKA_BROKERS=kafka:29092
      - OTEL_COLLECTOR_ENDPOINT=otel-collector:4317
    env_file: .env
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      otel-collector:
        condition: service_started

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
    depends_on:
      - zookeeper
    restart: always
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8089:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: taskforge
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    restart: always


  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./infra/otel-collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "8889:8889"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
    restart: always

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - prometheus
    restart: always

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "${DB_PORT}:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
